version: '3.3'
services:
    api:
      container_name: api
      restart: always
      build: .
      ports:
        - "4000:4000"
      links:
        - db
      environment:
        - URLDB=mongodb://db:27017/cafe

    db:
      container_name: mongo
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"